cctutorial/cctutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
#learning about relative imports below...
from polls import views


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('polls/', include('polls.urls'), name='polls'),
    path('', views.index),
]

cctutorial/polls/urls.py
from django.urls import path
from datetime import datetime

from polls import views

app_name = 'polls'

urlpatterns = [
    path('', views.home, name='polls'),
    path('index/', views.my_index, name='my_index'),
    path('most-popular/', views.most_popular_choice, name='most-popular-choice'),
    path('choices/<int:pk>/', views.choices, name='choices'),
    path('choices/', views.choices, name='choices'),
    path('questions/', views.questions, name='questions'),
    path('questions/<pub_date>', views.questions, name='questions'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('voter_limit/', views.voter_limit, name='voter_limit'),
]

cctutorial/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

cctutorial/polls/views.py
from datetime import date, datetime, time
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import render_to_string
from django.template import loader, RequestContext
from django.shortcuts import render_to_response, render, get_object_or_404
from polls.models import Choice, Question
#from django.utils.timezone import make_aware
from django.utils.timezone import now
from django.utils import timezone
from django.urls import reverse

#directed here from an empty path
def index(request):
    return render(request, 'polls/index.html')

#Queried once for all Question objects
def my_index(request):
    questions = Question.objects.all().order_by('pub_date')
    return render(request, 'polls/my_index.html', {'questions': questions})

#this is the "home" page for polls
#Had to rollback Django version to use render_to_response
def home(request):
    latest_question_list = Question.objects.only('question_text').order_by('-pub_date')[:5]
    output = ', '.join([p.question_text for p in latest_question_list])
    template = loader.get_template('polls/home.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return render_to_response('polls/home.html', context, request)

def most_popular_choice(request):
    choices = Choice.objects.all().order_by('votes').reverse()
    most_popular_choices = []
    max = choices[0].votes

    for choice in choices:
        if choice.votes >= max:
            most_popular_choices.append(choice)

    rendered = render_to_string('polls/most_popular_choice.html', {'most_popular_choices': most_popular_choices})
    return HttpResponse(rendered)


def choices(request, pk=None):

    if pk:
        #even though choices will only contain one choice in this case,
        #I made it a list to align with the list in the else block
        choice = get_object_or_404(Choice, pk=pk)
        choices = []
        choices.append(choice)
        questions = []
        questions = Question.objects.get(pk=choices[0].question_id)
        rendered = render_to_string('polls/choices.html', {'choices': choices, 'questions': questions})
        return HttpResponse(rendered)
    else:
        #Is there a better way to order these choices? 
        #using order_by.reverse() seems funky, but it works
        choices = Choice.objects.all().order_by('votes').reverse()
        questions = []

        rendered = render_to_string('polls/choices.html', {'choices': choices, 'questions': questions})
        return HttpResponse(rendered)


def questions(request, pub_date=None):

    #I used the full range of possible times to filter by a date at any time
    #To filter by date, the date should be entered in the url as YYYY-MM-DD
    # i.e.(..../questions/2021-07-10)
    if pub_date:
        pub_date_early = datetime.strptime(pub_date, "%Y-%m-%d").replace(hour=0, minute=0)
        pub_date_late = datetime.strptime(pub_date, "%Y-%m-%d").replace(hour=23, minute=59)
        questions = Question.objects.filter(pub_date__gte=pub_date_early).filter(pub_date__lte=pub_date_late)
    
    #This shows all questions published before the current datetime, effectively
    #showing all questions
    else:
        questions = Question.objects.filter(pub_date__lte=datetime.today())

    rendered = render_to_string('polls/questions.html', {'questions': questions})
    return HttpResponse(rendered)

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/vote.html', {
            'question': question,
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:voter_limit'))

def voter_limit(request):
    return render(request, 'polls/voter_limit.html')

cctutorial/polls/templates/polls/choices.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Choices page</title>
  </head>
  <body>
    <ul>
      {% if not choices %}
        <h4>There are no choices available :(</h4>
      {% endif %}

      {% for choice in choices %}
        <h1>{{ choice.question.question_text }}</h1>
        <p>{{ choice.choice_text }} -- {{ choice.votes }}  vote{{ choice.votes|pluralize }}</p>
      {% endfor %}
    </ul>
  </body>
</html>

cctutorial/polls/templates/polls/home.html
{% if latest_question_list %}
    {% for question in latest_question_list %}
        <a href="{% url 'polls:vote' question.id %}">
                {{ question.question_text }}</a>
        <p></p>
    {% endfor %}
{% else %}
    <p>No polls are available!</p>
{% endif %}

cctutorial/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home page :)</title>
  </head>
  <body>
    <!-- Learned that admin is a collection of paths and
    I had to reference 'admin:index' not 'admin' -->
    <a href="{% url 'admin:index' %}">Be the admin!</a>
    <p></p>
    <a href="{% url 'polls:polls' %}">Go to the polls!</a>
  </body>
</html>

cctutorial/polls/templates/polls/most_popular_choice.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Choices page</title>
  </head>
  <body>
    <ul>
      {% for choice in most_popular_choices %}
        <h1>Question id: {{ choice.question.pk }}</h1>
        <p>{{ choice.choice_text }} -- {{ choice.votes }}  vote{{ choice.votes|pluralize }}</p>
      {% endfor %}
    </ul>
  </body>
</html>

cctutorial/polls/templates/polls/my_index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>my_index</title>
  </head>
  <body>
    <ul>
      {% if not questions %}
        <h4>There are no questions available :(</h4>
      {% endif %}

      {% for question in questions %}
        <a>Published on: {{ question.pub_date }}</a>
        <p></p>
        <!-- Learning how to link to the right admin page was pretty cool :) -->
        <a href="{% url 'admin:polls_question_change' question.id %}">
                {{ question.question_text }}</a>
        <p></p>
      {% endfor %}
    </ul>
  </body>
</html>

cctutorial/polls/templates/polls/questions.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Choices page</title>
  </head>
  <body>
    <ul>
      {% if not questions %}
        <h4>There are no questions available :(</h4>
      {% endif %}

      {% for question in questions %}
        <h4>Published on: {{ question.pub_date }}</h4>
        <h1>{{ question.question_text }}</h1>
      {% endfor %}
    </ul>
  </body>
</html>

cctutorial/polls/templates/polls/vote.html
<h1>{{ question.question_text }}</h1>

<!-- {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %} -->

<h3>Please only submit one vote per day!</h3>

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    <p>This choice has {{ choice.votes }} votes</p>
{% endfor %}
<input type="submit" value="Vote">
</form>

cctutorial/polls/templates/polls/voter_limit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Choices page</title>
  </head>
  <body>
    <ul>
      <p>You just voted</p>
      <p>You can vote again tomorrow</p>
    </ul>
  </body>
</html>